// Generated by Wrangler on Thu Feb 13 2025 14:51:39 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	CONTENTFUL_CDA_ACCESS_TOKEN: string;
	CONTENTFUL_CMA_ACCESS_TOKEN: string;
	CONTENTFUL_SPACE_ID: string;
	NODE_ENV: string;
}
