const SUBDOMAIN = "dev";
export const SITE_STATIC_PATHS = ["", "resources", "blog"];
export const SITE_BASE_URL = `https://www.${SUBDOMAIN}.carlosmolero.com`;
export const SITE_BASE_URL_DEV = `http://dev.carlosmolero.com:3000`;
export const SITE_BASE_URL_DOMAIN_DEV = `dev.carlosmolero.com`
export const SITE_FETCHING_BASE_URL = SITE_BASE_URL
export const SITE_FETCHING_BASE_URL_DEV = `http://localhost:3000`;
export const SITE_EMAIL = "dev@carlosmolero.com";
export const SITE_PHONE_NUMBER = "+34674386776";
export const SITE_X_URL = "https://x.com/iscarlosmolero";
export const SITE_X_HANDLE = "@iscarlosmolero";
export const SITE_LINKEDIN_URL = "https://www.linkedin.com/in/iscarlosmolero/";
export const SITE_STREET_ADDRESS = "";
export const SITE_ADDRESS_LOCALITY = "";
export const SITE_ADDRESS_REGION = "";
export const SITE_ADDRESS_POSTAL_CODE = "";
export const SITE_DEFAULT_LOCALE = "en"
export const SITE_SUPPORTED_LOCALES = ["es", "en", "zh"]
